@host= localhost
@port= 3000


## Test Api Gateway
GET http://{{host}}:{{port}}/api/v1
Content-Type: application/json

### Test microservice Brand
GET http://{{host}}:{{port}}/api/v1/catalog/brand/status


### Get All Brand
GET http://{{host}}:{{port}}/api/v1/catalog/brand/
Content-Type: application/json